eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#feign\u81EA\u5E26\u65AD\u8DEF\u5668\u4F46\u662F\u6CA1\u6709\u6253\u5F00\uFF0C\u9700\u624B\u52A8\u8BBE\u7F6E\u6253\u5F00
feign:
  hystrix:
    enabled: true
